### ISSUE TITLE
No Option for field 9 in  workstations section

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#3]
In lmn v7 you can set the device typ in field 9. This should be possible with the webUI, too. Currently there is no such field / dropdown.

**Comment by PLanB2008** [comment]
Should be fixed in current code. Package will be updated soon

**Comment by zefanja** [comment]
It is not fixed, because LMNv7 has different roles then v6.2. See `man devices.csv`.

**Comment by PLanB2008** [comment]
Should be fixed in a6547419b785d207e523fbd9b428eca4906dd54f 

please check
